'use client'

import Link from 'next/link'
import { ArrowUpRight, CalendarDays, ChevronRight } from 'lucide-react'
import { nominees, events } from '@/lib/mock-data'
import { Brand } from '@/components/brand/brand'

export function Pill({ children, tone = '' }: { children: React.ReactNode; tone?: string }) { return <span className={`pill ${tone}`}>{children}</span> }
export function Button({ children, onClick, secondary = false }: { children: React.ReactNode; onClick?: () => void; secondary?: boolean }) { return <button onClick={onClick} className={secondary ? 'button secondary' : 'button'}>{children}</button> }
export function PublicHeader() { return <header className="site-header"><Link href="/"><Brand /></Link><nav><Link href="/about">About us</Link><Link href="/programs">Our impact</Link><Link href="/awards">Awards</Link><Link href="/events">Events</Link><Link href="/news">Stories</Link></nav><div className="header-actions"><Link className="portal-link" href="/nominee">Portal <ArrowUpRight size={15}/></Link><Link className="button" href="/contact">Support her work</Link></div></header> }
export function PublicFooter() { return <footer className="footer"><Brand /><p>A Sierra Leone where every girl can become who she imagines.</p><div><Link href="/contact">Contact</Link><Link href="/partners">Partners</Link></div><small>© 2026 Girl Pikin For Betteh Foundation · Demo interface</small></footer> }
export function SectionHeading({ label, title, copy }: { label: string; title: React.ReactNode; copy?: string }) { return <div className="section-heading"><div><Pill>{label}</Pill><h2>{title}</h2></div>{copy && <p>{copy}</p>}</div> }
export function NomineeCard({ nominee = nominees[0] }: { nominee?: typeof nominees[number] }) { return <article className="panel nominee-card"><div className={`mini-avatar ${nominee.color}`}>{nominee.initials}</div><Pill tone="coral">{nominee.category}</Pill><h3>{nominee.name}</h3><p>{nominee.institution}</p><div className="card-actions"><Link className="text-button" href={`/nominees/${nominee.code}`}>View profile <ArrowUpRight size={15}/></Link><Link className="button" href={`/vote/${nominee.code}`}>Vote now</Link></div></article> }
export function EventCard({ event = events[0] }: { event?: typeof events[number] }) { return <article className="event-card"><div className="event-date"><b>{event.date.split(' ')[0]}</b><span>{event.date.split(' ')[1]}</span></div><Pill tone="coral">{event.type}</Pill><h3>{event.title}</h3><p><CalendarDays size={15}/> {event.location}</p><footer><span>{event.price}</span><Link aria-label={`View ${event.title}`} href={`/events/${event.slug}`}><ArrowUpRight size={17}/></Link></footer></article> }
export function PublicHome() { return <><PublicHeader/><main id="top"><section className="hero"><div className="hero-copy"><Pill tone="coral">Sierra Leone · Demo edition</Pill><h1>Every girl deserves a <em>better</em> tomorrow.</h1><p>Girl Pikin For Betteh Foundation creates safe spaces, opens doors and backs the bold ideas of girls across Sierra Leone.</p><div className="hero-actions"><Link className="button" href="/about">Our story <ChevronRight size={17}/></Link><Link className="text-button" href="/awards">Explore awards <ArrowUpRight size={16}/></Link></div></div><div className="hero-art"><div className="sun-tag">2026<br/><b>AWARDS</b></div><div className="portrait"><div className="portrait-overlay"><span>“The future<br/>looks like<br/><strong>us.</strong>”</span></div></div></div></section><section className="section" id="impact"><SectionHeading label="What we do" title={<>Small shifts.<br/><em>Big futures.</em></>} copy="We believe in the power of a girl with support behind her. Our work is practical, personal and built to last."/><div className="impact-grid"><article className="impact-card teal"><h3>Safe spaces</h3><p>Trusted places to learn, play and be heard.</p></article><article className="impact-card coral-card"><h3>New skills</h3><p>Tools and confidence for the next chapter.</p></article><article className="impact-card gold-card"><h3>Bright voices</h3><p>Backing girls to lead change on their terms.</p></article></div></section><section className="section"><SectionHeading label="Meet the nominees" title={<>People making<br/><em>her future brighter.</em></>}/><div className="nominee-grid">{nominees.map(n=><NomineeCard key={n.code} nominee={n}/>)}</div></section><section className="section"><SectionHeading label="Gather with us" title={<>Events with<br/><em>purpose.</em></>} /><div className="event-grid">{events.slice(0,2).map(e=><EventCard event={e} key={e.slug}/>)}</div></section></main><PublicFooter/></> }
export function AwardsPlaceholder(){return <><PublicHeader/><main className="section"><SectionHeading label="Awards" title={<>Celebrating<br/><em>bold ideas.</em></>} copy="A representative frontend view for the 2026 awards edition."/><div className="nominee-grid">{nominees.map(n=><NomineeCard nominee={n} key={n.code}/>)}</div></main><PublicFooter/></>}

