'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { ArrowUpRight } from 'lucide-react'
import { Brand } from '@/components/brand/brand'
import { stats, bars } from '@/lib/mock-data'
export function StatusBadge({children, tone=''}:{children:React.ReactNode;tone?:string}){return <span className={`pill ${tone}`}>{children}</span>}
const nomineeLinks=[['Dashboard','/nominee'],['My Profile','/nominee/profile'],['Vote Performance','/nominee/performance'],['Campaign Tools','/nominee/campaign'],['Announcements','/nominee/announcements'],['Documents','/nominee/documents'],['Ceremony Pass','/nominee/pass']]
const adminLinks=[['Dashboard','/admin'],['Programs','/admin/programs'],['Awards','/admin/awards'],['Nominees','/admin/awards/nominees'],['Voting','/admin/awards/voting'],['Results','/admin/awards/results'],['Events','/admin/events'],['Ticket Types','/admin/events/ticket-types'],['Orders','/admin/events/orders'],['Tickets','/admin/events/tickets'],['Check-ins','/admin/events/checkins'],['Finance','/admin/finance'],['Payments','/admin/finance/payments'],['Reconciliation','/admin/finance/reconciliation'],['Refunds','/admin/finance/refunds'],['Reports','/admin/finance/reports'],['Content','/admin/content'],['Users & Roles','/admin/users'],['Audit Logs','/admin/audit'],['Settings','/admin/settings']]
export function PortalSidebar({admin=false}:{admin?:boolean}){const path=usePathname();const links=admin?adminLinks:nomineeLinks;return <aside className="portal-side"><Link href="/"><Brand/></Link><div className="side-label">{admin?'Admin workspace':'Nominee space'}</div>{links.map(([label,href])=><Link className={path===href?'side-active':''} href={href} key={href}>{label}</Link>)}<div className="side-bottom"><Link href="/">View public site <ArrowUpRight size={15}/></Link><span>{admin?'Aminata · Admin':'Mariama Koroma'}</span></div></aside>}
export function PortalHeader({admin=false}:{admin?:boolean}){return <header className="portal-header"><span className="crumb">{admin?'Admin':'Nominee'} portal / <b>{admin?'Workspace':'Dashboard'}</b></span><Link className="button secondary" href="/">Exit portal</Link></header>}
export function PortalLayout({children,admin=false}:{children:React.ReactNode;admin?:boolean}){return <main className="portal"><PortalSidebar admin={admin}/><div className="portal-main"><PortalHeader admin={admin}/>{children}</div></main>}
export function PortalDashboard({admin=false}:{admin?:boolean}){return <div className="portal-content"><div className="portal-title"><div><StatusBadge tone={admin?'teal':'coral'}>{admin?'Demo workspace':'Community Champion'}</StatusBadge><h1>Good morning,<br/><em>{admin?'Aminata.':'Mariama.'}</em></h1><p>{admin?'A representative operations overview.':'Here’s how your campaign is moving.'}</p></div><div className="profile-avatar">{admin?'AD':'MK'}</div></div><div className="stat-row">{(admin?stats:[{label:'Total votes',value:'1,284',change:'Sample data'},{label:'Votes gained today',value:'86',change:'Sample data'},{label:'Rank',value:'#04',change:'Demo ranking'}]).map(s=><div className="stat-box" key={s.label}><span>{s.label}</span><b>{s.value}</b><small>{s.change}</small></div>)}</div><div className="portal-grid"><section className="panel chart-panel"><span className="eyebrow">Activity overview</span><h2>Momentum this month.</h2><div className="bars">{bars.map((b,i)=><i style={{height:`${b}%`}} key={i}/>)}</div></section><section className="panel share-panel"><span className="eyebrow">Quick actions</span><h2>{admin?'Keep things moving.':'Make it easy to vote for you.'}</h2><p>Frontend-only demo tools ready for future wiring.</p><Link className="button" href={admin?'/scan':'/vote/50MISA26001'}>{admin?'Open scanner':'View voting page'}</Link></section></div></div>}
