'use client'

import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { usePathname } from 'next/navigation'
import { Brand } from '@/components/brand/brand'
import { stats, bars } from '@/lib/mock-data'

export function StatusBadge({ children, tone = '' }: { children: React.ReactNode; tone?: string }) { return <span className={`pill ${tone}`}>{children}</span> }

const adminGroups = [
  ['MAIN', [['Dashboard', '/admin'], ['Programs', '/admin/programs']]],
  ['AWARDS', [['Overview', '/admin/awards'], ['Editions', '/admin/awards/editions'], ['Categories', '/admin/awards/categories'], ['Applications', '/admin/awards/applications'], ['Nominees', '/admin/awards/nominees'], ['Voting', '/admin/awards/voting'], ['Results', '/admin/awards/results']]],
  ['EVENTS', [['Events', '/admin/events'], ['Ticket Types', '/admin/events/ticket-types'], ['Orders', '/admin/events/orders'], ['Tickets', '/admin/events/tickets'], ['Check-ins', '/admin/events/checkins']]],
  ['FINANCE', [['Overview', '/admin/finance'], ['Payments', '/admin/finance/payments'], ['Reconciliation', '/admin/finance/reconciliation'], ['Refunds', '/admin/finance/refunds'], ['Reports', '/admin/finance/reports']]],
  ['MANAGEMENT', [['Communication', '/admin/communication'], ['Content', '/admin/content'], ['Users & Roles', '/admin/users'], ['Audit Logs', '/admin/audit'], ['Settings', '/admin/settings']]],
] as const
const nomineeLinks = [['Dashboard', '/nominee'], ['My Profile', '/nominee/profile'], ['Vote Performance', '/nominee/performance'], ['Campaign Tools', '/nominee/campaign'], ['Announcements', '/nominee/announcements'], ['Documents', '/nominee/documents'], ['Ceremony Pass', '/nominee/pass']] as const
function active(path: string, href: string) { return href === '/admin' || href === '/nominee' ? path === href : path === href || path.startsWith(`${href}/`) }
function routeLabel(path: string, admin: boolean) { const labels: Record<string, string> = { '/admin':'Dashboard', '/admin/programs':'Programs', '/admin/awards':'Awards', '/admin/awards/editions':'Awards / Editions', '/admin/awards/categories':'Awards / Categories', '/admin/awards/applications':'Awards / Applications', '/admin/awards/nominees':'Awards / Nominees', '/admin/awards/voting':'Awards / Voting', '/admin/awards/results':'Awards / Results', '/admin/events':'Events', '/admin/events/ticket-types':'Events / Ticket Types', '/admin/events/orders':'Events / Orders', '/admin/events/tickets':'Events / Tickets', '/admin/events/checkins':'Events / Check-ins', '/admin/finance':'Finance', '/admin/finance/payments':'Finance / Payments', '/admin/finance/reconciliation':'Finance / Reconciliation', '/admin/finance/refunds':'Finance / Refunds', '/admin/finance/reports':'Finance / Reports', '/admin/communication':'Communication', '/admin/content':'Content', '/admin/users':'Users & Roles', '/admin/audit':'Audit Logs', '/admin/settings':'Settings', '/nominee':'Dashboard', '/nominee/profile':'My Profile', '/nominee/performance':'Vote Performance', '/nominee/campaign':'Campaign Tools', '/nominee/announcements':'Announcements', '/nominee/documents':'Documents', '/nominee/pass':'Ceremony Pass' }; return `${admin ? 'Admin' : 'Nominee'} / ${labels[path] || 'Workspace'}` }
export function PortalSidebar({ admin = false }: { admin?: boolean }) { const path = usePathname(); return <aside className="portal-side"><Link href="/"><Brand /></Link><div className="side-label">{admin ? 'Admin workspace' : 'Nominee space'}</div>{admin ? adminGroups.map(([group, links]) => <div key={group}><div className="side-label">{group}</div>{links.map(([label, href]) => <Link className={active(path, href) ? 'side-active' : ''} href={href} key={href}>{label}</Link>)}</div>) : nomineeLinks.map(([label, href]) => <Link className={active(path, href) ? 'side-active' : ''} href={href} key={href}>{label}</Link>)}<div className="side-bottom"><Link href="/">View public site <ArrowUpRight size={15} /></Link><span>{admin ? 'Aminata · Admin' : 'Mariama Koroma'}</span></div></aside> }
export function PortalHeader({ admin = false }: { admin?: boolean }) { const path = usePathname(); return <header className="portal-header"><span className="crumb">{routeLabel(path, admin)}</span><Link className="button secondary" href="/">Exit portal</Link></header> }
export function PortalLayout({ children, admin = false }: { children: React.ReactNode; admin?: boolean }) { return <main className="portal"><PortalSidebar admin={admin} /><div className="portal-main"><PortalHeader admin={admin} />{children}</div></main> }
export function PortalDashboard({ admin = false }: { admin?: boolean }) { return <div className="portal-content"><div className="portal-title"><div><StatusBadge tone={admin ? 'teal' : 'coral'}>{admin ? 'Demo workspace' : 'Community Champion'}</StatusBadge><h1>Good morning,<br /><em>{admin ? 'Aminata.' : 'Mariama.'}</em></h1><p>{admin ? 'A representative operations overview.' : 'Here’s how your campaign is moving.'}</p></div><div className="profile-avatar">{admin ? 'AD' : 'MK'}</div></div><div className="stat-row">{(admin ? stats : [{ label: 'Total votes', value: '1,284', change: 'Sample data' }, { label: 'Votes gained today', value: '86', change: 'Sample data' }, { label: 'Rank', value: '#04', change: 'Demo ranking' }]).map(s => <div className="stat-box" key={s.label}><span>{s.label}</span><b>{s.value}</b><small>{s.change}</small></div>)}</div><div className="portal-grid"><section className="panel chart-panel"><span className="eyebrow">Activity overview</span><h2>Momentum this month.</h2><div className="bars">{bars.map((b, i) => <i style={{ height: `${b}%` }} key={i} />)}</div></section><section className="panel share-panel"><span className="eyebrow">Quick actions</span><h2>{admin ? 'Keep things moving.' : 'Make it easy to vote for you.'}</h2><p>Frontend-only demo tools ready for future wiring.</p><Link className="button" href={admin ? '/scan' : '/vote/50MISA26001'}>{admin ? 'Open scanner' : 'View voting page'}</Link></section></div></div> }
