'use client'

import { useState } from 'react'
import { ArrowUpRight, CalendarDays, Check, ChevronRight, CircleDollarSign, Copy, Heart, Menu, QrCode, ScanLine, Share2, Sparkles, Ticket, Users, X } from 'lucide-react'
import { bars, events, nominees, news, stats } from '@/lib/mock-data'

type Surface = 'public' | 'nominee' | 'admin' | 'scanner'

const nav = ['About us', 'Our impact', 'Awards', 'Events', 'Stories']

function Mark() { return <div className="mark"><span>GP</span><i /></div> }
function Pill({ children, tone = 'default' }: { children: React.ReactNode; tone?: string }) { return <span className={`pill ${tone}`}>{children}</span> }
function Button({ children, onClick, secondary = false }: { children: React.ReactNode; onClick?: () => void; secondary?: boolean }) { return <button onClick={onClick} className={secondary ? 'button secondary' : 'button'}>{children}</button> }
function SurfaceSwitcher({ surface, setSurface }: { surface: Surface; setSurface: (v: Surface) => void }) { return <div className="surface-switcher">{(['public', 'nominee', 'admin', 'scanner'] as Surface[]).map((item) => <button key={item} className={surface === item ? 'active' : ''} onClick={() => setSurface(item)}>{item === 'public' ? 'Public website' : item === 'nominee' ? 'Nominee portal' : item === 'admin' ? 'Admin portal' : 'Event scanner'}</button>)}</div> }
function Header({ setSurface }: { setSurface: (v: Surface) => void }) { const [open, setOpen] = useState(false); return <header className="site-header"><a className="brand" href="#top"><Mark /><span>Girl Pikin<br /><b>For Betteh</b></span></a><nav>{nav.map((n) => <a href={`#${n.toLowerCase().replace(' ', '-')}`} key={n}>{n}</a>)}</nav><div className="header-actions"><button className="portal-link" onClick={() => setSurface('nominee')}>Portal <ArrowUpRight size={15} /></button><Button onClick={() => setSurface('public')}>Support her work</Button></div><button className="menu-btn" aria-label="Open navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>{open && <div className="mobile-nav">{nav.map(n => <a key={n} href="#top" onClick={() => setOpen(false)}>{n}</a>)}<Button onClick={() => setSurface('nominee')}>Open portal</Button></div>}</header> }

function PublicPage({ setSurface }: { setSurface: (v: Surface) => void }) { const [liked, setLiked] = useState(false); return <>
  <Header setSurface={setSurface} />
  <main id="top"><section className="hero"><div className="hero-copy"><Pill tone="coral">Sierra Leone · Est. 2018</Pill><h1>Every girl deserves a <em>better</em> tomorrow.</h1><p>Girl Pikin For Betteh Foundation creates safe spaces, opens doors and backs the bold ideas of girls across Sierra Leone.</p><div className="hero-actions"><Button onClick={() => document.getElementById('impact')?.scrollIntoView({ behavior: 'smooth' })}>See our impact <ChevronRight size={17} /></Button><button className="text-button" onClick={() => setSurface('public')}>Our story <ArrowUpRight size={16} /></button></div><div className="hero-note"><div className="avatar-stack"><span>AM</span><span>FK</span><span>JS</span><span>+1k</span></div><span>Join 1,200+ people backing her future</span></div></div><div className="hero-art"><div className="sun-tag">2026<br /><b>AWARDS</b></div><div className="portrait"><div className="portrait-overlay"><span>“The future<br />looks like<br /><strong>us.</strong>”</span><small>— Fatmata, 17<br />Young leader</small></div></div><div className="scribble">FOR<br />BETTEH</div></div></section>
  <section className="marquee"><span>She leads</span><span>She dreams</span><span>She builds</span><span>She belongs</span><span>She leads</span><span>She dreams</span></section>
  <section className="impact-section section" id="impact"><div className="section-intro"><Pill>What we do</Pill><h2>Small shifts.<br /><em>Big futures.</em></h2><p>We believe in the power of a girl with support behind her. Our work is practical, personal and built to last.</p><a className="text-button" href="#programs">Explore our approach <ArrowUpRight size={16} /></a></div><div className="impact-grid"><article className="impact-card teal"><span className="number">01</span><Users size={26} /><h3>Safe spaces</h3><p>Trusted places to learn, play and be heard.</p></article><article className="impact-card coral-card"><span className="number">02</span><Sparkles size={26} /><h3>New skills</h3><p>Tools and confidence for the next chapter.</p></article><article className="impact-card gold-card"><span className="number">03</span><Heart size={26} /><h3>Bright voices</h3><p>Backing girls to lead change on their terms.</p></article></div></section>
  <section className="awards-section section" id="awards"><div className="award-copy"><Pill tone="gold">Now open · 2026 edition</Pill><h2>The people making<br /><em>her future brighter.</em></h2><p>The Girl Pikin Awards celebrate the everyday heroes who show up, speak up and make room for girls to thrive.</p><Button onClick={() => setSurface('public')}>Explore the nominees <ArrowUpRight size={16} /></Button><div className="award-meta"><span><b>18</b> nominees</span><span><b>06</b> categories</span><span><b>12</b> days left</span></div></div><div className="vote-card"><div className="vote-top"><Pill tone="dark">People’s choice</Pill><span>Closes 30 Sep</span></div><h3>Who gets your vote?</h3><div className="mini-nominees">{nominees.map((n, i) => <button key={n.name} onClick={() => setLiked(i === 0)} className={liked && i === 0 ? 'selected' : ''}><span className={`mini-avatar ${n.color}`}>{n.initials}</span><span><b>{n.name}</b><small>{n.category}</small></span>{liked && i === 0 ? <Check size={18} /> : <Heart size={17} />}</button>)}</div><button className="vote-link" onClick={() => setSurface('public')}>View all nominees <ChevronRight size={15} /></button></div></section>
  <section className="section" id="programs"><div className="section-heading"><div><Pill>Our programmes</Pill><h2>Backing her, <em>at every step.</em></h2></div><p>From first ideas to bold leadership, our programmes meet girls where they are and help them go further.</p></div><div className="program-list"><div><span className="program-icon coral-bg">01</span><h3>She Can</h3><p>Life skills & mentorship</p><ArrowUpRight /></div><div><span className="program-icon teal-bg">02</span><h3>Her Ideas</h3><p>Innovation & enterprise</p><ArrowUpRight /></div><div><span className="program-icon gold-bg">03</span><h3>Speak Up</h3><p>Voice & leadership</p><ArrowUpRight /></div></div></section>
  <section className="events-section section" id="events"><div className="section-heading"><div><Pill>On the calendar</Pill><h2>Come be part of it.</h2></div><a className="text-button" href="#events">See all events <ArrowUpRight size={16} /></a></div><div className="event-grid">{events.map(e => <article className="event-card" key={e.title}><div className="event-date"><b>{e.date.split(' ')[0]}</b><span>{e.date.split(' ')[1]}</span></div><Pill tone="coral">{e.type}</Pill><h3>{e.title}</h3><p><CalendarDays size={15} /> {e.location}</p><footer><span>{e.price}</span><button aria-label={`View ${e.title}`}><ArrowUpRight size={17} /></button></footer></article>)}</div></section>
  <section className="stories-section section"><div className="section-heading"><div><Pill>From the journal</Pill><h2>Good news travels.</h2></div><a className="text-button" href="#journal">Read the journal <ArrowUpRight size={16} /></a></div><div className="news-grid">{news.map((item, i) => <article key={item.title} className={`news-card news-${i}`}><Pill>{item.tag}</Pill><h3>{item.title}</h3><span>{item.date} <ArrowUpRight size={15} /></span></article>)}</div></section>
  <footer className="footer"><div className="brand"><Mark /><span>Girl Pikin<br /><b>For Betteh</b></span></div><p>A Sierra Leone where every girl can become who she imagines.</p><div><a href="#top">Instagram</a><a href="#top">LinkedIn</a><a href="#top">Contact</a></div><small>© 2026 Girl Pikin For Betteh Foundation</small></footer></main></> }

function Portal({ admin = false, setSurface }: { admin?: boolean; setSurface: (v: Surface) => void }) { const [tab, setTab] = useState(admin ? 'Overview' : 'My profile'); const tabs = admin ? ['Overview', 'Awards', 'Nominees', 'Ticket orders', 'Finance'] : ['My profile', 'My campaign', 'Materials', 'Pass']; return <main className="portal"><aside className="portal-side"><a className="brand" href="#top"><Mark /><span>Girl Pikin<br /><b>For Betteh</b></span></a><div className="side-label">{admin ? 'Workspace' : 'Nominee space'}</div>{tabs.map(t => <button className={tab === t ? 'side-active' : ''} key={t} onClick={() => setTab(t)}>{t}</button>)}<div className="side-bottom"><button onClick={() => setSurface('public')}>View public site <ArrowUpRight size={15} /></button><span><span className="user-dot">{admin ? 'AD' : 'MK'}</span>{admin ? 'Aminata · Admin' : 'Mariama Koroma'}</span></div></aside><div className="portal-main"><header className="portal-header"><button className="mobile-back" onClick={() => setSurface('public')}>←</button><span className="crumb">{admin ? 'Admin portal' : 'Nominee portal'} / <b>{tab}</b></span><div><Button secondary onClick={() => setSurface('public')}>Exit portal</Button></div></header>{admin ? <AdminContent tab={tab} setSurface={setSurface} /> : <NomineeContent tab={tab} />}</div></main> }
function NomineeContent({ tab }: { tab: string }) { return <div className="portal-content"><div className="portal-title"><div><Pill tone="coral">Community Champion</Pill><h1>Good morning,<br /><em>Mariama.</em></h1><p>Your voice is already making a difference. Here’s how your campaign is moving.</p></div><div className="profile-avatar">MK</div></div><div className="stat-row">{[{ label: 'Total votes', value: '1,284', change: '+18.4%' }, { label: 'Profile views', value: '4,892', change: '+32.1%' }, { label: 'Days to ceremony', value: '89', change: '28 Nov 2026' }].map(s => <div className="stat-box" key={s.label}><span>{s.label}</span><b>{s.value}</b><small>{s.change}</small></div>)}</div><div className="portal-grid"><section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">Vote activity</span><h2>Votes are climbing.</h2></div><select aria-label="Chart period"><option>Last 30 days</option></select></div><div className="bars">{bars.map((b, i) => <i style={{ height: `${b}%` }} key={i} className={i > 7 ? 'current' : ''} />)}</div><div className="chart-labels"><span>Aug 01</span><span>Aug 15</span><span>Aug 30</span></div></section><section className="panel share-panel"><span className="eyebrow">Your campaign kit</span><h2>Make it easy<br />to vote for you.</h2><p>Share your profile with your people and let them know what their vote means.</p><Button><Share2 size={16} /> Share profile</Button><button className="copy-button"><Copy size={15} /> Copy campaign link</button><div className="qr-block"><QrCode size={54} /><span>Scan to vote<br /><b>girlpikin.sl/mariama</b></span></div></section></div><section className="panel announcement"><div><Pill tone="gold">Important</Pill><h2>Ceremony passes are ready.</h2><p>Your nominee pass and guest details are available in the Pass tab.</p></div><ChevronRight /></section></div> }
function AdminContent({ tab, setSurface }: { tab: string; setSurface: (v: Surface) => void }) { return <div className="portal-content"><div className="portal-title"><div><Pill tone="teal">Live workspace</Pill><h1>{tab === 'Overview' ? <>Good morning,<br /><em>Aminata.</em></> : tab}</h1><p>{tab === 'Overview' ? 'Here’s what’s happening across the foundation today.' : 'Manage the 2026 Girl Pikin Awards programme.'}</p></div><Button onClick={() => setSurface('scanner')}><ScanLine size={16} /> Open scanner</Button></div><div className="stat-row admin-stats">{stats.map(s => <div className="stat-box" key={s.label}><span>{s.label}</span><b>{s.value}</b><small>{s.change}</small></div>)}</div><div className="portal-grid"><section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">Activity overview</span><h2>Momentum this month.</h2></div><select aria-label="Chart period"><option>August 2026</option></select></div><div className="bars">{bars.map((b, i) => <i style={{ height: `${b}%` }} key={i} className={i > 7 ? 'current' : ''} />)}</div><div className="chart-labels"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span></div></section><section className="panel live-panel"><div className="panel-heading"><div><span className="eyebrow">Live now</span><h2>Voting activity</h2></div><span className="live-dot">● Live</span></div>{nominees.map(n => <div className="rank-row" key={n.name}><span className={`mini-avatar ${n.color}`}>{n.initials}</span><span><b>{n.name}</b><small>{n.category}</small></span><strong>{n.votes.toLocaleString()}</strong></div>)}<button className="vote-link">Open monitoring <ChevronRight size={15} /></button></section></div><section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">Recent orders</span><h2>Ticket sales</h2></div><button className="text-button">View all <ArrowUpRight size={15} /></button></div>{['#GP-2408 · Fatmata Jalloh', '#GP-2407 · Mohamed Kamara', '#GP-2406 · Sarah Conteh'].map((x, i) => <div className="table-row" key={x}><span><b>{x}</b><small>{i === 0 ? 'Bintumani Conference Centre' : 'Girl Pikin Awards 2026'}</small></span><Pill tone={i === 1 ? 'gold' : 'teal'}>{i === 1 ? 'Pending' : 'Paid'}</Pill><strong>NLe {i === 1 ? '500' : '1,000'}</strong></div>)}</section></div> }

function Scanner({ setSurface }: { setSurface: (v: Surface) => void }) { const [state, setState] = useState<'ready' | 'valid' | 'used' | 'invalid'>('ready'); return <main className="scanner"><header><button onClick={() => setSurface('public')}><Mark /><span>Girl Pikin <b>Events</b></span></button><div><Pill tone="teal">Live event</Pill><span>28 Nov 2026 · 18:42</span></div></header><div className="scanner-body"><div className="scanner-heading"><Pill tone="gold">Awards night 2026</Pill><h1>Ticket check-in</h1><p>Scan a QR code or enter a ticket number to verify entry.</p></div>{state === 'ready' ? <><div className="scan-frame"><ScanLine size={38} /><span>Position QR code inside the frame</span><i /><i /><i /><i /></div><div className="manual"><input placeholder="Enter ticket number e.g. GP-2408" aria-label="Ticket number" /><Button onClick={() => setState('valid')}>Check ticket</Button></div></> : <div className={`scan-result ${state}`}><div className="result-icon">{state === 'valid' ? <Check /> : state === 'used' ? <Ticket /> : <X />}</div><Pill tone={state === 'valid' ? 'teal' : 'coral'}>{state === 'valid' ? 'Valid ticket' : state === 'used' ? 'Already used' : 'Ticket not found'}</Pill><h2>{state === 'valid' ? 'Welcome, Fatmata.' : state === 'used' ? 'This ticket was checked in.' : 'We couldn’t verify this ticket.'}</h2><p>{state === 'valid' ? 'General admission · Order #GP-2408' : state === 'used' ? 'Checked in today at 18:12 by scanner 02.' : 'Check the number and try again.'}</p><Button onClick={() => setState('ready')}>Scan another ticket</Button></div>}<div className="scanner-recent"><div><span className="eyebrow">Recent scans</span><button className="text-button">View log <ArrowUpRight size={15} /></button></div><p><span className="scan-status valid" />#GP-2408 <b>Fatmata Jalloh</b><small>Just now</small></p><p><span className="scan-status used" />#GP-2389 <b>Mohamed Kamara</b><small>2 min ago</small></p></div><div className="demo-states"><span>Demo states:</span><button onClick={() => setState('valid')}>Valid</button><button onClick={() => setState('used')}>Used</button><button onClick={() => setState('invalid')}>Invalid</button></div></div></main> }

export default function Page() { const [surface, setSurface] = useState<Surface>('public'); return <><SurfaceSwitcher surface={surface} setSurface={setSurface} />{surface === 'public' && <PublicPage setSurface={setSurface} />}{surface === 'nominee' && <Portal setSurface={setSurface} />}{surface === 'admin' && <Portal admin setSurface={setSurface} />}{surface === 'scanner' && <Scanner setSurface={setSurface} />}</> }
