-- 0001_auth_rbac.sql
-- Girl Pikin For Betteh Foundation
-- Foundation schema: profiles, roles, permissions, user-role assignments and audit log.
-- Designed for a fresh Supabase project.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text,
  avatar_url text,
  status text not null default 'active'
    check (status in ('active', 'suspended', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null unique,
  description text,
  is_system boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.permissions (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role_id uuid not null references public.roles(id) on delete cascade,
  permission_id uuid not null references public.permissions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id uuid not null references public.roles(id) on delete cascade,
  scope_type text not null default 'global'
    check (scope_type in ('global', 'award', 'award_edition', 'event')),
  scope_id uuid,
  assigned_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  check (
    (scope_type = 'global' and scope_id is null)
    or
    (scope_type <> 'global' and scope_id is not null)
  )
);

create unique index if not exists user_roles_global_unique
  on public.user_roles(user_id, role_id)
  where scope_id is null;

create unique index if not exists user_roles_scoped_unique
  on public.user_roles(user_id, role_id, scope_type, scope_id)
  where scope_id is not null;

create index if not exists user_roles_user_idx on public.user_roles(user_id);
create index if not exists user_roles_scope_idx on public.user_roles(scope_type, scope_id);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  old_data jsonb,
  new_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_actor_idx on public.audit_logs(actor_user_id);
create index if not exists audit_logs_entity_idx on public.audit_logs(entity_type, entity_id);
create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      split_part(coalesce(new.email, ''), '@', 1),
      ''
    )
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.has_role(
  requested_role_code text,
  requested_scope_type text default null,
  requested_scope_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.code = requested_role_code
      and (
        ur.scope_id is null
        or (
          requested_scope_type is not null
          and requested_scope_id is not null
          and ur.scope_type = requested_scope_type
          and ur.scope_id = requested_scope_id
        )
      )
  );
$$;

create or replace function public.has_permission(
  requested_permission_code text,
  requested_scope_type text default null,
  requested_scope_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.role_permissions rp on rp.role_id = ur.role_id
    join public.permissions p on p.id = rp.permission_id
    where ur.user_id = auth.uid()
      and p.code = requested_permission_code
      and (
        ur.scope_id is null
        or (
          requested_scope_type is not null
          and requested_scope_id is not null
          and ur.scope_type = requested_scope_type
          and ur.scope_id = requested_scope_id
        )
      )
  );
$$;

create or replace function public.current_role_codes()
returns text[]
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(array_agg(distinct r.code order by r.code), array[]::text[])
  from public.user_roles ur
  join public.roles r on r.id = ur.role_id
  where ur.user_id = auth.uid()
    and ur.scope_id is null;
$$;

-- One-time helper for the SQL editor or a trusted backend using the secret key.
-- It is intentionally unavailable to normal browser users.
create or replace function public.bootstrap_super_admin(target_email text)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  target_user_id uuid;
  super_admin_role_id uuid;
begin
  select id
  into target_user_id
  from auth.users
  where lower(email) = lower(target_email)
  limit 1;

  if target_user_id is null then
    raise exception 'No auth user found for email %', target_email;
  end if;

  select id
  into super_admin_role_id
  from public.roles
  where code = 'super_admin';

  if super_admin_role_id is null then
    raise exception 'super_admin role has not been seeded';
  end if;

  insert into public.user_roles (user_id, role_id, scope_type, scope_id)
  values (target_user_id, super_admin_role_id, 'global', null)
  on conflict do nothing;

  return target_user_id;
end;
$$;

revoke all on function public.bootstrap_super_admin(text) from public;
revoke all on function public.bootstrap_super_admin(text) from anon;
revoke all on function public.bootstrap_super_admin(text) from authenticated;
grant execute on function public.bootstrap_super_admin(text) to service_role;

insert into public.roles (code, name, description) values
  ('super_admin', 'Super Admin', 'Full platform administration'),
  ('awards_manager', 'Awards Manager', 'Manages awards, editions and results workflows'),
  ('nomination_officer', 'Nomination Officer', 'Reviews nominee applications and verification'),
  ('voting_manager', 'Voting Manager', 'Manages voting configuration and operations'),
  ('event_manager', 'Event Manager', 'Manages events, ticketing and check-in operations'),
  ('finance_officer', 'Finance Officer', 'Manages payments, reconciliation, refunds and reports'),
  ('checkin_officer', 'Check-In Officer', 'Operates event admission and ticket scanning'),
  ('content_manager', 'Content Manager', 'Manages public content and programmes'),
  ('auditor', 'Auditor', 'Read-only access to audit and operational records'),
  ('nominee', 'Nominee', 'Access to the nominee portal')
on conflict (code) do update
set name = excluded.name,
    description = excluded.description;

insert into public.permissions (code, name, description) values
  ('admin.access', 'Access administration', 'Allows access to the administration workspace'),
  ('programs.manage', 'Manage programmes', 'Create and maintain programme content'),
  ('awards.manage', 'Manage awards', 'Create and maintain awards, editions and categories'),
  ('nominations.review', 'Review nominations', 'Review applications and supporting documents'),
  ('voting.manage', 'Manage voting', 'Manage vote settings and operational vote records'),
  ('results.manage', 'Manage results', 'Reconcile, approve and publish award results'),
  ('events.manage', 'Manage events', 'Manage events, ticket types and event operations'),
  ('finance.manage', 'Manage finance', 'Manage payments, reconciliation, refunds and finance reports'),
  ('checkin.use', 'Use check-in', 'Validate tickets and record admissions'),
  ('content.manage', 'Manage content', 'Manage public site content'),
  ('users.manage', 'Manage users and roles', 'Manage staff access and permissions'),
  ('audit.read', 'Read audit log', 'Read audit and operational history'),
  ('settings.manage', 'Manage platform settings', 'Manage controlled platform configuration'),
  ('nominee.portal', 'Access nominee portal', 'Access the nominee self-service workspace')
on conflict (code) do update
set name = excluded.name,
    description = excluded.description;

-- Super Admin receives every permission.
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.code = 'super_admin'
on conflict do nothing;

-- Staff role permission mappings.
with mappings(role_code, permission_code) as (
  values
    ('awards_manager', 'admin.access'),
    ('awards_manager', 'awards.manage'),
    ('awards_manager', 'nominations.review'),
    ('awards_manager', 'results.manage'),

    ('nomination_officer', 'admin.access'),
    ('nomination_officer', 'nominations.review'),

    ('voting_manager', 'admin.access'),
    ('voting_manager', 'voting.manage'),

    ('event_manager', 'admin.access'),
    ('event_manager', 'events.manage'),
    ('event_manager', 'checkin.use'),

    ('finance_officer', 'admin.access'),
    ('finance_officer', 'finance.manage'),

    ('checkin_officer', 'admin.access'),
    ('checkin_officer', 'checkin.use'),

    ('content_manager', 'admin.access'),
    ('content_manager', 'programs.manage'),
    ('content_manager', 'content.manage'),

    ('auditor', 'admin.access'),
    ('auditor', 'audit.read'),

    ('nominee', 'nominee.portal')
)
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from mappings m
join public.roles r on r.code = m.role_code
join public.permissions p on p.code = m.permission_code
on conflict do nothing;

alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.user_roles enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists profiles_admin_read on public.profiles;
create policy profiles_admin_read
on public.profiles
for select
to authenticated
using (public.has_permission('users.manage') or public.has_permission('audit.read'));

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists roles_admin_read on public.roles;
create policy roles_admin_read
on public.roles
for select
to authenticated
using (public.has_permission('users.manage') or public.has_permission('audit.read'));

drop policy if exists permissions_admin_read on public.permissions;
create policy permissions_admin_read
on public.permissions
for select
to authenticated
using (public.has_permission('users.manage') or public.has_permission('audit.read'));

drop policy if exists role_permissions_admin_read on public.role_permissions;
create policy role_permissions_admin_read
on public.role_permissions
for select
to authenticated
using (public.has_permission('users.manage') or public.has_permission('audit.read'));

drop policy if exists user_roles_self_read on public.user_roles;
create policy user_roles_self_read
on public.user_roles
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists user_roles_admin_read on public.user_roles;
create policy user_roles_admin_read
on public.user_roles
for select
to authenticated
using (public.has_permission('users.manage') or public.has_permission('audit.read'));

drop policy if exists audit_logs_authorized_read on public.audit_logs;
create policy audit_logs_authorized_read
on public.audit_logs
for select
to authenticated
using (public.has_permission('audit.read'));

revoke all on table public.profiles from anon;
revoke all on table public.profiles from authenticated;
grant select on table public.profiles to authenticated;
grant update (full_name, phone, avatar_url) on table public.profiles to authenticated;

revoke all on table public.roles from anon;
revoke all on table public.permissions from anon;
revoke all on table public.role_permissions from anon;
revoke all on table public.user_roles from anon;
revoke all on table public.audit_logs from anon;

grant select on table public.roles to authenticated;
grant select on table public.permissions to authenticated;
grant select on table public.role_permissions to authenticated;
grant select on table public.user_roles to authenticated;
grant select on table public.audit_logs to authenticated;

grant execute on function public.has_role(text, text, uuid) to authenticated;
grant execute on function public.has_permission(text, text, uuid) to authenticated;
grant execute on function public.current_role_codes() to authenticated;

commit;
