-- 0003_payments_voting_ticketing.sql
-- Central payments, append-only vote ledger, ticket orders, individual tickets and check-ins.

begin;

create table if not exists public.vote_orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  nominee_id uuid not null references public.nominees(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(14,2) not null check (unit_price > 0),
  total_amount numeric(14,2)
    generated always as (quantity * unit_price) stored,
  currency text not null default 'SLE',
  buyer_name text,
  buyer_email text,
  buyer_phone text,
  status text not null default 'pending'
    check (status in ('pending', 'payment_pending', 'paid', 'failed', 'cancelled', 'refunded')),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vote_orders_nominee_idx on public.vote_orders(nominee_id);
create index if not exists vote_orders_status_idx on public.vote_orders(status, created_at desc);

create table if not exists public.ticket_orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  event_id uuid not null references public.events(id) on delete restrict,
  purchaser_name text not null,
  purchaser_email text,
  purchaser_phone text,
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  total_amount numeric(14,2) not null default 0 check (total_amount >= 0),
  currency text not null default 'SLE',
  status text not null default 'pending'
    check (status in ('pending', 'payment_pending', 'paid', 'cancelled', 'refunded', 'partially_refunded')),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ticket_orders_event_idx on public.ticket_orders(event_id);
create index if not exists ticket_orders_status_idx on public.ticket_orders(status, created_at desc);

create table if not exists public.ticket_order_items (
  id uuid primary key default gen_random_uuid(),
  ticket_order_id uuid not null references public.ticket_orders(id) on delete cascade,
  ticket_type_id uuid not null references public.ticket_types(id) on delete restrict,
  ticket_type_name text not null,
  pricing_type text not null
    check (pricing_type in ('fixed', 'donation', 'free')),
  quantity integer not null check (quantity > 0),
  admissions_per_unit integer not null default 1 check (admissions_per_unit > 0),
  unit_amount numeric(14,2) not null check (unit_amount >= 0),
  line_total numeric(14,2)
    generated always as (quantity * unit_amount) stored,
  created_at timestamptz not null default now()
);

create index if not exists ticket_order_items_order_idx
  on public.ticket_order_items(ticket_order_id);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  payment_type text not null
    check (payment_type in ('vote', 'ticket', 'donation')),
  vote_order_id uuid references public.vote_orders(id) on delete restrict,
  ticket_order_id uuid references public.ticket_orders(id) on delete restrict,
  provider text not null,
  provider_transaction_id text,
  idempotency_key text not null unique,
  amount numeric(14,2) not null check (amount >= 0),
  currency text not null default 'SLE',
  status text not null default 'pending'
    check (status in (
      'pending',
      'processing',
      'succeeded',
      'failed',
      'cancelled',
      'refunded',
      'partially_refunded',
      'reversed'
    )),
  payer_name text,
  payer_email text,
  payer_phone text,
  provider_payload jsonb not null default '{}'::jsonb,
  failure_reason text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (payment_type = 'vote' and vote_order_id is not null and ticket_order_id is null)
    or
    (payment_type = 'ticket' and ticket_order_id is not null and vote_order_id is null)
    or
    (payment_type = 'donation' and vote_order_id is null and ticket_order_id is null)
  )
);

create unique index if not exists payments_provider_transaction_unique
  on public.payments(provider, provider_transaction_id)
  where provider_transaction_id is not null;

create index if not exists payments_vote_order_idx on public.payments(vote_order_id);
create index if not exists payments_ticket_order_idx on public.payments(ticket_order_id);
create index if not exists payments_status_idx on public.payments(status, created_at desc);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  payment_id uuid references public.payments(id) on delete set null,
  event_type text,
  payload jsonb not null default '{}'::jsonb,
  processed_at timestamptz,
  processing_error text,
  received_at timestamptz not null default now(),
  unique (provider, provider_event_id)
);

create index if not exists payment_events_payment_idx on public.payment_events(payment_id);

-- Append-only ledger. Never edit nominee totals directly.
create table if not exists public.vote_ledger (
  id bigint generated by default as identity primary key,
  nominee_id uuid not null references public.nominees(id) on delete restrict,
  vote_order_id uuid references public.vote_orders(id) on delete restrict,
  payment_id uuid references public.payments(id) on delete restrict,
  entry_type text not null
    check (entry_type in ('payment', 'adjustment', 'reversal', 'refund')),
  quantity_delta integer not null check (quantity_delta <> 0),
  source_key text not null unique,
  reason text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  check (
    (entry_type = 'payment' and quantity_delta > 0 and payment_id is not null)
    or
    (entry_type in ('reversal', 'refund') and quantity_delta < 0)
    or
    (entry_type = 'adjustment')
  )
);

create index if not exists vote_ledger_nominee_idx on public.vote_ledger(nominee_id, created_at);
create index if not exists vote_ledger_order_idx on public.vote_ledger(vote_order_id);

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_order_id uuid not null references public.ticket_orders(id) on delete restrict,
  ticket_order_item_id uuid not null references public.ticket_order_items(id) on delete restrict,
  event_id uuid not null references public.events(id) on delete restrict,
  ticket_type_id uuid not null references public.ticket_types(id) on delete restrict,
  ticket_code text not null unique,
  qr_token_hash text not null unique,
  status text not null default 'active'
    check (status in ('active', 'cancelled', 'refunded', 'reissued')),
  holder_name text,
  admission_sequence integer not null default 1 check (admission_sequence > 0),
  reissued_from_ticket_id uuid references public.tickets(id) on delete set null,
  issued_at timestamptz not null default now(),
  cancelled_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists tickets_event_idx on public.tickets(event_id);
create index if not exists tickets_order_idx on public.tickets(ticket_order_id);
create index if not exists tickets_status_idx on public.tickets(event_id, status);

create table if not exists public.ticket_checkins (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.tickets(id) on delete restrict,
  event_id uuid not null references public.events(id) on delete restrict,
  checked_in_by uuid references public.profiles(id) on delete set null,
  checked_in_at timestamptz not null default now(),
  device_label text,
  notes text,
  unique (ticket_id)
);

create index if not exists ticket_checkins_event_idx on public.ticket_checkins(event_id, checked_in_at desc);

create table if not exists public.refunds (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null references public.payments(id) on delete restrict,
  amount numeric(14,2) not null check (amount > 0),
  reason text not null,
  provider_refund_id text,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'succeeded', 'failed', 'cancelled')),
  requested_by uuid references public.profiles(id) on delete set null,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists refunds_provider_refund_unique
  on public.refunds(provider_refund_id)
  where provider_refund_id is not null;

-- Timestamp triggers.
do $$
declare
  t text;
begin
  foreach t in array array[
    'vote_orders',
    'ticket_orders',
    'payments',
    'tickets',
    'refunds'
  ]
  loop
    execute format('drop trigger if exists %I_set_updated_at on public.%I', t, t);
    execute format(
      'create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      t,
      t
    );
  end loop;
end $$;

-- Public aggregate function. It exposes only nominee code/id/rank/total,
-- never payer identity, payment details or vote-order details.
create or replace function public.get_public_nominee_vote_totals(
  p_award_edition_id uuid
)
returns table (
  nominee_id uuid,
  nominee_code text,
  total_votes bigint,
  rank_position bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with edition as (
    select id, leaderboard_visibility, leaderboard_frozen_at
    from public.award_editions
    where id = p_award_edition_id
      and is_public = true
      and leaderboard_visibility <> 'hidden'
  ),
  totals as (
    select
      n.id as nominee_id,
      n.nominee_code,
      coalesce(sum(
        case
          when e.leaderboard_visibility = 'frozen'
            and e.leaderboard_frozen_at is not null
            and vl.created_at > e.leaderboard_frozen_at
          then 0
          else vl.quantity_delta
        end
      ), 0)::bigint as total_votes
    from edition e
    join public.nominees n
      on n.award_edition_id = e.id
     and n.is_public = true
     and n.status = 'published'
    left join public.vote_ledger vl on vl.nominee_id = n.id
    group by n.id, n.nominee_code
  )
  select
    t.nominee_id,
    t.nominee_code,
    t.total_votes,
    dense_rank() over (order by t.total_votes desc, t.nominee_code asc)::bigint as rank_position
  from totals t
  order by rank_position, t.nominee_code;
$$;

create or replace function public.get_my_nominee_vote_summary()
returns table (
  nominee_id uuid,
  nominee_code text,
  total_votes bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    n.id,
    n.nominee_code,
    coalesce(sum(vl.quantity_delta), 0)::bigint
  from public.nominees n
  left join public.vote_ledger vl on vl.nominee_id = n.id
  where n.auth_user_id = auth.uid()
  group by n.id, n.nominee_code
  order by n.nominee_code;
$$;

grant execute on function public.get_public_nominee_vote_totals(uuid) to anon, authenticated;
grant execute on function public.get_my_nominee_vote_summary() to authenticated;

-- RLS.
alter table public.vote_orders enable row level security;
alter table public.ticket_orders enable row level security;
alter table public.ticket_order_items enable row level security;
alter table public.payments enable row level security;
alter table public.payment_events enable row level security;
alter table public.vote_ledger enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_checkins enable row level security;
alter table public.refunds enable row level security;

drop policy if exists vote_orders_staff_read on public.vote_orders;
create policy vote_orders_staff_read
on public.vote_orders for select
to authenticated
using (
  public.has_permission('voting.manage')
  or public.has_permission('finance.manage')
  or public.has_permission('audit.read')
);

drop policy if exists vote_ledger_staff_read on public.vote_ledger;
create policy vote_ledger_staff_read
on public.vote_ledger for select
to authenticated
using (
  public.has_permission('voting.manage')
  or public.has_permission('finance.manage')
  or public.has_permission('results.manage')
  or public.has_permission('audit.read')
);

drop policy if exists ticket_orders_staff_read on public.ticket_orders;
create policy ticket_orders_staff_read
on public.ticket_orders for select
to authenticated
using (
  public.has_permission('events.manage', 'event', event_id)
  or public.has_permission('finance.manage')
  or public.has_permission('audit.read')
);

drop policy if exists ticket_order_items_staff_read on public.ticket_order_items;
create policy ticket_order_items_staff_read
on public.ticket_order_items for select
to authenticated
using (
  exists (
    select 1
    from public.ticket_orders o
    where o.id = ticket_order_items.ticket_order_id
      and (
        public.has_permission('events.manage', 'event', o.event_id)
        or public.has_permission('finance.manage')
        or public.has_permission('audit.read')
      )
  )
);

drop policy if exists payments_staff_read on public.payments;
create policy payments_staff_read
on public.payments for select
to authenticated
using (
  public.has_permission('finance.manage')
  or public.has_permission('audit.read')
);

drop policy if exists payment_events_staff_read on public.payment_events;
create policy payment_events_staff_read
on public.payment_events for select
to authenticated
using (
  public.has_permission('finance.manage')
  or public.has_permission('audit.read')
);

drop policy if exists tickets_staff_read on public.tickets;
create policy tickets_staff_read
on public.tickets for select
to authenticated
using (
  public.has_permission('events.manage', 'event', event_id)
  or public.has_permission('checkin.use', 'event', event_id)
  or public.has_permission('finance.manage')
  or public.has_permission('audit.read')
);

drop policy if exists checkins_staff_read on public.ticket_checkins;
create policy checkins_staff_read
on public.ticket_checkins for select
to authenticated
using (
  public.has_permission('events.manage', 'event', event_id)
  or public.has_permission('checkin.use', 'event', event_id)
  or public.has_permission('audit.read')
);

drop policy if exists checkins_officer_insert on public.ticket_checkins;
create policy checkins_officer_insert
on public.ticket_checkins for insert
to authenticated
with check (
  checked_in_by = auth.uid()
  and public.has_permission('checkin.use', 'event', event_id)
);

drop policy if exists refunds_staff_read on public.refunds;
create policy refunds_staff_read
on public.refunds for select
to authenticated
using (
  public.has_permission('finance.manage')
  or public.has_permission('audit.read')
);

grant select on table public.vote_orders to authenticated;
grant select on table public.ticket_orders to authenticated;
grant select on table public.ticket_order_items to authenticated;
grant select on table public.payments to authenticated;
grant select on table public.payment_events to authenticated;
grant select on table public.vote_ledger to authenticated;
grant select on table public.tickets to authenticated;
grant select on table public.ticket_checkins to authenticated;
grant insert on table public.ticket_checkins to authenticated;
grant select on table public.refunds to authenticated;

-- Keep direct operational writes server-only.
revoke insert, update, delete on table public.vote_orders from anon, authenticated;
revoke insert, update, delete on table public.ticket_orders from anon, authenticated;
revoke insert, update, delete on table public.ticket_order_items from anon, authenticated;
revoke insert, update, delete on table public.payments from anon, authenticated;
revoke insert, update, delete on table public.payment_events from anon, authenticated;
revoke insert, update, delete on table public.vote_ledger from anon, authenticated;
revoke insert, update, delete on table public.tickets from anon, authenticated;
revoke update, delete on table public.ticket_checkins from anon, authenticated;
revoke insert, update, delete on table public.refunds from anon, authenticated;

commit;
